id: IB8D5C933
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T09:15:45+00:00'
last_modified: '2022-06-08T02:24:33.697611+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15222
  title: སྐོར་ཚོམས་སྟོང་ཐུན་བཅུ་གཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7CBC:
      image_group_id: I1KG22763
      title: ''
      total_pages: 226
      order: 1
      base_file: 7CBC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
