id: P004626
initial_creation_type: ocr
source_metadata:
  id: bdr:W15222
  title: སྐོར་ཚོམས་སྟོང་ཐུན་བཅུ་གཅིག
  author: ''
  volumes:
    e63bd2e3c0ac4118baf5d7cc8b935345:
      image_group_id: I1KG22763
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
